- name: Core | groups | staff | create group
  group:
    name: staff

- name: Core | groups | staff | copy sudoers file
  copy:
    src: groups/staff/sudoers
    dest: /etc/sudoers.d/staff
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s