- name: IntelliJ Idea | install IntelliJ Idea CE 2024.3.4
  unarchive:
    src: https://download.jetbrains.com/idea/ideaIC-2024.3.4.tar.gz
    dest: /opt/
    creates: /opt/idea-IC-243.25659.39/bin/idea
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: IntelliJ Idea | create versionless link
  file:
    src: /opt/idea-IC-243.25659.39
    dest: /opt/idea-IC
    state: link
    force: yes

- name: IntelliJ Idea | copy desktop entry
  copy:
    src: jetbrains-idea-ce.desktop
    dest: /usr/local/share/applications/jetbrains-idea-ce.desktop
    owner: root
    group: root
    mode: 0644