- name: Core | users | guest | create session configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/guest-session
    - /etc/guest-session/skel
    - /var/lib/guest-session
    - /var/lib/guest-session/mnt
  
- name: Core | users | guest | create session mount directories
  file:
    path: "{{ item }}"
    state: directory
    owner: guest
    group: guest
    mode: 0755
  loop:
    - /var/lib/guest-session/mnt/data
    - /var/lib/guest-session/mnt/home

- name: Core | users | guest | allocate loopback file for guest data
  command: fallocate -l 1G /var/lib/guest-session/data.img
  args:
    creates: /var/lib/guest-session/data.img

- name: Core | users | guest | allocate loopback file for guest home
  command: fallocate -l 8G /var/lib/guest-session/home.img
  args:
    creates: /var/lib/guest-session/home.img

- name: Core | users | guest | create ext4 filesystem for guest data
  community.general.filesystem:
    fstype: ext4
    dev: /var/lib/guest-session/data.img
    opts: -m 0

- name: Core | users | guest | create ext4 filesystem for guest home
  community.general.filesystem:
    fstype: ext4
    dev: /var/lib/guest-session/home.img
    opts: -m 0
