- name: Replica | users | guest | create session configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/guest-session
    - /etc/guest-session/skel
    - /var/lib/guest-session
    - /var/lib/guest-session/mnt
  
- name: Replica | users | guest | create session mount directories
  file:
    path: "{{ item }}"
    state: directory
    owner: guest
    group: guest
    mode: 0755
  loop:
    - /var/lib/guest-session/mnt/data
    - /var/lib/guest-session/mnt/home

- name: Replica | users | guest | allocate loopback file for guest data
  command: fallocate -l 1G /var/lib/guest-session/data.img
  args:
    creates: /var/lib/guest-session/data.img

- name: Core | users | guest | allocate loopback file for guest home
  command: fallocate -l 8G /var/lib/guest-session/home.img
  args:
    creates: /var/lib/guest-session/home.img

- name: Core | users | guest | create ext4 filesystem for guest data
  community.general.filesystem:
    fstype: ext4
    dev: /var/lib/guest-session/data.img
    opts: -m 0

- name: Core | users | guest | create ext4 filesystem for guest home
  community.general.filesystem:
    fstype: ext4
    dev: /var/lib/guest-session/home.img
    opts: -m 0

- name: Replica | users | guest | add script to GDM PostLogin handler
  blockinfile:
    path: /etc/gdm3/PostLogin/Default
    insertbefore: ".*\\.init.sh.*"
    block: |
      if [ "${USER}" = "guest" ]; then
          DATA_LOOPBACK=/var/lib/guest-session/mnt/data
          HOME_LOOPBACK=/var/lib/guest-session/mnt/home

          mount -o loop /var/lib/guest-session/data.img ${DATA_LOOPBACK} || exit 1
          mount -o loop /var/lib/guest-session/home.img ${HOME_LOOPBACK} || {
              umount ${DATA_LOOPBACK}
              exit 1
          }

          rm -rf ${HOME_LOOPBACK}/lower ${HOME_LOOPBACK}/upper ${HOME_LOOPBACK}/work

          mkdir ${HOME_LOOPBACK}/lower ${HOME_LOOPBACK}/upper ${HOME_LOOPBACK}/work
          chown ${USER}:${USER} ${HOME_LOOPBACK}/upper ${HOME_LOOPBACK}/work

          chown ${USER}:${USER} ${DATA_LOOPBACK}

          bindfs -r --map=0/1000:@0/@1000 /etc/guest-session/skel ${HOME_LOOPBACK}/lower || {
              umount ${HOME_LOOPBACK}
              umount ${DATA_LOOPBACK}
              exit 1
          }

          mount -t overlay -o lowerdir=${HOME_LOOPBACK}/lower,upperdir=${HOME_LOOPBACK}/upper,workdir=${HOME_LOOPBACK}/work overlay ${HOME} || {
              umount ${HOME_LOOPBACK}/lower
              umount ${HOME_LOOPBACK}
              umount ${DATA_LOOPBACK}
              exit 1
          }

          ln -s -f ${DATA_LOOPBACK} "${HOME}/Área compartilhada"
      fi
    append_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GUEST SESSION"

- name: Replica | users | guest | add script to GDM PostSession handler
  blockinfile:
    path: /etc/gdm3/PostSession/Default
    insertafter: EOF
    block: |
      if [ "${USER}" = "guest" ]; then
          DATA_LOOPBACK=/var/lib/guest-session/mnt/data
          HOME_LOOPBACK=/var/lib/guest-session/mnt/home

          pkill -u ${USER} -9

          umount ${HOME} || umount -l ${HOME}
          umount ${HOME_LOOPBACK}/lower || umount -l ${HOME_LOOPBACK}/lower
          umount ${HOME_LOOPBACK} || umount -l ${HOME_LOOPBACK}
      fi
    append_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GUEST SESSION"